name: Sentiment Demo UI
language: nodejs
variables:
  - name: sentiment
    inputType: FreeText
    description: The topic to read from
    defaultValue: sentiment
    required: true
  - name: messages
    inputType: FreeText
    description: The topic to read from
    defaultValue: messages
    required: true
  - name: drafts
    inputType: FreeText
    description: ''
    defaultValue: drafts
    required: true
  - name: drafts_sentiment
    inputType: FreeText
    description: ''
    defaultValue: drafts_sentiment
    required: false
  - name: messages_sanitized
    inputType: OutputTopic
    description: ''
    defaultValue: messages_sanitized
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
