name: Sentiment analysis
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the raw data input topic
    defaultValue: messages
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output for the Hugging Face model score
    defaultValue: sentiment
    required: true
  - name: output_sanitized
    inputType: OutputTopic
    description: ''
    defaultValue: messages_sanitized
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
